# SPDX-FileCopyrightText: 2025 NOI Techpark <digital@noi.bz.it>
#
# SPDX-License-Identifier: CC0-1.0
#
services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:11
    container_name: forgejo
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ${DATA_VOLUME}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./custom/public/:/data/gitea/public/:ro
      - ./custom/templates/:/data/gitea/templates/:ro
    deploy:
      resources:
        limits:
          cpus: '2.00'
          memory: '3G'
          
  anubis:
    image: ghcr.io/techarohq/anubis:latest
    container_name: anubis
      # see here for config options
      # https://github.com/TecharoHQ/anubis/blob/main/docs/docs/admin/installation.mdx
    environment:
      SERVE_ROBOTS_TXT: true
      TARGET: http://forgejo:3000
      JWT_RESTRICTION_HEADER: 
    ports:
      - '${SERVER_PORT_WEB}:8923'
    healthcheck:
      test: ["CMD", "anubis", "--healthcheck"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 500ms
      
  caddy:
    profiles:
      - dev
    image: caddy:2
    ports:
      - ${LOCAL_DEV_PORT:-8080}:80
    volumes:
      - ./infrastructure/local.caddyfile:/etc/caddy/Caddyfile
